name: PR Check

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  flutter-test:
    name: Flutter test and build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Java のセットアップ
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Flutter のセットアップ
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.3'
          channel: 'stable'
          cache: true

      - name: Gradle キャッシュ
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: CocoaPods キャッシュ
        uses: actions/cache@v3
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Firebase設定ファイルの作成
        env:
          FIREBASE_OPTIONS: ${{ secrets.FIREBASE_OPTIONS }}
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
          GOOGLE_SERVICES_PLIST: ${{ secrets.GOOGLE_SERVICES_PLIST }}
        run: |
          # デコードする前に環境変数の存在確認
          if [ -z "$FIREBASE_OPTIONS" ]; then
            echo "Error: FIREBASE_OPTIONS is not set"
            exit 1
          fi

          echo "$FIREBASE_OPTIONS" | base64 --decode > lib/firebase_options.dart
          echo "$GOOGLE_SERVICES_JSON" | base64 --decode > android/app/google-services.json
          echo "$GOOGLE_SERVICES_PLIST" | base64 --decode > ios/Runner/GoogleService-Info.plist

          chmod 600 lib/firebase_options.dart
          chmod 600 android/app/google-services.json
          chmod 600 ios/Runner/GoogleService-Info.plist

          # ファイルサイズの確認
          ls -l lib/firebase_options.dart
          ls -l android/app/google-services.json
          ls -l ios/Runner/GoogleService-Info.plist

      - name: 依存関係のインストール
        run: flutter pub get

      - name: フォーマットチェック
        run: make format

      - name: 静的解析
        run: flutter analyze

      - name: テスト実行
        run: flutter test

      - name: Android ビルド
        run: flutter build apk --debug

      - name: UnityFramework.podspec 作成
        run: make create-podspec

      - name: iOS ビルド準備
        run: |
          cd ios
          pod install --repo-update

      - name: iOS ビルド
        run: flutter build ios --debug --no-codesign

      - name: pub キャッシュの保存
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.PUB_CACHE }}
            **/.dart_tool
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-
