name: PR Check

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  flutter-test:
    name: Flutter test and build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Java のセットアップ
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Flutter のセットアップ
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.3'
          channel: 'stable'
          cache: true

      - name: Gradle キャッシュ
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: CocoaPods キャッシュ
        uses: actions/cache@v3
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Firebase設定ファイルの作成
        env:
          FIREBASE_OPTIONS: ${{ secrets.FIREBASE_OPTIONS }}
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
          GOOGLE_SERVICES_PLIST: ${{ secrets.GOOGLE_SERVICES_PLIST }}
        run: |
          # ディレクトリの確認
          ls -la lib/

          # firebase_options.dartの作成
          echo "$FIREBASE_OPTIONS" > lib/firebase_options.dart

          # 作成されたファイルの内容確認（機密情報は適宜マスク）
          echo "=== firebase_options.dart の内容 ==="
          cat lib/firebase_options.dart | sed 's/apiKey: "[^"]*"/apiKey: "***"/g'

          echo "$GOOGLE_SERVICES_JSON" > android/app/google-services.json
          echo "$GOOGLE_SERVICES_PLIST" > ios/Runner/GoogleService-Info.plist

          # ファイルが作成されたか確認
          echo "=== ファイル確認 ==="
          ls -la lib/firebase_options.dart
          ls -la android/app/google-services.json
          ls -la ios/Runner/GoogleService-Info.plist

      - name: 依存関係のインストール
        run: flutter pub get

      - name: フォーマットチェック
        run: make format

      - name: 静的解析
        run: flutter analyze

      - name: テスト実行
        run: flutter test

      - name: Android ビルド
        run: flutter build apk --debug

      - name: UnityFramework.podspec 作成
        run: make create-podspec

      - name: iOS ビルド準備
        run: |
          cd ios
          pod install --repo-update

      - name: iOS ビルド
        run: flutter build ios --debug --no-codesign

      - name: pub キャッシュの保存
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.PUB_CACHE }}
            **/.dart_tool
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-
