name: PR Check

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  flutter-test:
    name: Flutter test
    runs-on: macos-latest
    environment: development

    steps:
      - uses: actions/checkout@v4

      - name: Flutter のセットアップ
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.3'
          channel: 'stable'
          cache: true

      - name: 依存関係のインストール
        run: flutter pub get

      - name: フォーマットチェック
        run: make format

      - name: 静的解析
        run: flutter analyze

      - name: テスト実行
        run: flutter test
